# For more information: https://laravel.com/docs/sail
version: "3"
services:

  app:
    image: mtbossa/raspberry-prod:staging
    restart: always
    ports:
      - "45691:45691"
    env_file:
      - .env
    volumes:
      - ${MEDIAS_FOLDER_PATH}:/intus/public/medias
      - ${DB_FOLDER_PATH}:/intus/data
      - ${LOGS_FOLDER_PATH}:/intus/logs

# For testing with local Laravel Sail backend
# API_URL at .env must be the name of the Laravel Docker container e.g.: http://laravel:80
# networks:
#   default:
#     name: intus-backend_sail # Change the name to Laravel Sail network's name
#     external: true
