# For more information: https://laravel.com/docs/sail
version: '3'
services:
    app:
        image: intus:prod
        restart: always
        ports:
            - '3030:3030'
        env_file:
          - .env
        volumes:
            - '/home/mtbossa/intus/medias:/intus/public/medias'
        depends_on:
          - mongodb
    mongodb:
        image: 'mongo:latest'
        container_name: intus-mongo
        ports:
            - '${DB_PORT}:27017'
        environment:
          MONGO_INITDB_DATABASE: ${DB_NAME}
          MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
          MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
        restart: always
        volumes:
            - 'intus-mongodb:/db/data'
volumes:
    intus-mongodb: