# For more information: https://laravel.com/docs/sail
version: '3'
services:
    app:
        image: mtbossa/raspberry-prod:latest
        restart: always
        ports:
            - '3030:3030'
        env_file:
          - .env
        volumes:
            - '/intus/medias:/intus/public/medias'
        depends_on:
          - mongodb
    mongodb:
        image: 'mongo:latest'
        container_name: intus-mongo
        ports:
            - '${DB_PORT}:27017'
        environment:
          MONGO_INITDB_DATABASE: ${DB_NAME}
          MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
          MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
        restart: always
        volumes:
            - 'intus-mongodb:/db/data'
    watchtower:
        image: containrrr/watchtower
        environment:
            REPO_USER: ${REPO_USER}
            REPO_PASS: ${REPO_PASS}
            WATCHTOWER_DEBUG: ${WATCHTOWER_DEBUG}
            WATCHTOWER_CLEANUP: "true"
            WATCHTOWER_SCHEDULE: "0 0 * * *"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
    intus-mongodb: