name: Build Docker staging image
on:
  push:
    branches: ["main", "staging"]
jobs:
  build:
    name: Build and push to Docker Hub
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # This step is run when the branch is production
      - name: Sets env vars for production
        run: |
          echo "DOCKER_IMAGE_NAME=mtbossa/raspberry-prod:latest" >> $GITHUB_ENV
        if: github.ref_name === "main"

      # This step is run when the branch is staging
      - name: Sets env vars for staging
        run: |
          echo "DOCKER_IMAGE_NAME=mtbossa/raspberry-prod:staging" >> $GITHUB_ENV
        if: github.ref_name === "staging"

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ${{env.DOCKER_IMAGE_NAME}}
          file: Dockerfile.production
